name: Sync to Gitee

on:
  push:
    branches:
      - main  # 默认为 main 分支，如果你的分支叫 master 请自行修改

jobs:
  push-to-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@v1.4
        with:
          src: github/${{ github.repository_owner }}
          dst: gitee/pigeonWaWa
          dst_key: ${{ secrets.GITEE_TOKEN }}  # 使用刚才配置的密钥
          src_token: ''
          account_type: user
          static_list: ${{ github.event.repository.name }}
